version: "3.9"

services:
  gitea:
    image: gitea/gitea:1.19.0
    environment:
      - USER_UID=1000
      - USER_GID=100
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__webhook__ALLOWED_HOST_LIST=*
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - gitea-db
  
  gitea-db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - gitea-db-data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:lts-community
    restart: always
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - gitea

networks:
  gitea:

volumes:
  gitea-data:
  gitea-db-data:
