version: "3.9"

services:
  bot:
    image: gitea-sonarqube-community-bot:1.0.0
    environment:
      - PORT=4000
      - GITEA_URL=http://172.17.0.1:3000
      - SONARQUBE_URL=http://172.17.0.1:9000

    ports:
      - "4000:4000"
    volumes:
      - ./traces:/app/traces
      - ./repos:/app/repos
    networks:
      - gitea-bot

networks:
  gitea-bot:

volumes:
  bot-traces:
  bot-repos:
